#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
    echo "Checking npm session..."
    exec < /dev/tty && yarn login --scope @bloom-trade
	exec < /dev/tty && yarn publish:packages
fi

